# Generated by Django 3.2 on 2023-02-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_category', models.CharField(choices=[('fantagy', 'ファンタジー・SF'), ('robot', 'ロボット・メカ'), ('action', 'アクション・バトル'), ('comedy', 'コメディ・ギャグ'), ('love_comedy', '恋愛・ラブコメ'), ('life', '日常・ほのぼの'), ('horror', 'ホラー・サスペンス・推理'), ('sports', 'スポーツ・競技'), ('war', '戦争・ミリタリー'), ('other', 'その他')], max_length=100)),
                ('sub_category', models.CharField(blank=True, choices=[('fantagy', 'ファンタジー・SF'), ('robot', 'ロボット・メカ'), ('action', 'アクション・バトル'), ('comedy', 'コメディ・ギャグ'), ('love_comedy', '恋愛・ラブコメ'), ('life', '日常・ほのぼの'), ('horror', 'ホラー・サスペンス・推理'), ('sports', 'スポーツ・競技'), ('war', '戦争・ミリタリー'), ('other', 'その他')], max_length=100, null=True)),
            ],
        ),
    ]
