# Generated by Django 3.2 on 2023-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
