# Generated by Django 3.2 on 2023-02-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
