# Generated by Django 3.2 on 2023-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_anime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='comment',
            field=models.TextField(default='無し'),
        ),
    ]
