# Generated by Django 3.2 on 2023-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20230227_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='main_category',
            field=models.CharField(choices=[('ファンタジー', 'ファンタジー・SF'), ('ロボット', 'ロボット・メカ'), ('アクション', 'アクション・バトル'), ('コメディ', 'コメディ・ギャグ'), ('恋愛・ラブコメディ', '恋愛・ラブコメ'), ('日常', '日常・ほのぼの'), ('ホラー', 'ホラー・サスペンス・推理'), ('スポーツ', 'スポーツ・競技'), ('戦争・ミリタリー', '戦争・ミリタリー'), ('学園', '学園'), ('その他', 'その他')], max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('ファンタジー', 'ファンタジー・SF'), ('ロボット', 'ロボット・メカ'), ('アクション', 'アクション・バトル'), ('コメディ', 'コメディ・ギャグ'), ('恋愛・ラブコメディ', '恋愛・ラブコメ'), ('日常', '日常・ほのぼの'), ('ホラー', 'ホラー・サスペンス・推理'), ('スポーツ', 'スポーツ・競技'), ('戦争・ミリタリー', '戦争・ミリタリー'), ('学園', '学園'), ('その他', 'その他')], max_length=100, null=True),
        ),
    ]
