# Generated by Django 4.0.1 on 2023-03-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_review',
            old_name='anime',
            new_name='game',
        ),
    ]
